[fix] fix npm
Signed-off-by: WessiH <wessim.harmel1@gmail.com>

diff --git a/apps/agents/Worker/france-nuage-agent/DEBIAN/postinst b/apps/agents/Worker/france-nuage-agent/DEBIAN/postinst
--- a/apps/agents/Worker/france-nuage-agent/DEBIAN/postinst
+++ b/apps/agents/Worker/france-nuage-agent/DEBIAN/postinst
@@ -3,37 +3,50 @@ set -e
 
 # Create a new group and user for the service if they don't exist
 if ! getent group france-nuage-agent > /dev/null 2>&1; then
-    sudo groupadd -r france-nuage-agent
+    groupadd -r france-nuage-agent
 fi
 
 if ! getent passwd france-nuage-agent > /dev/null 2>&1; then
-    sudo useradd -r -s /usr/sbin/nologin -g france-nuage-agent france-nuage-agent
+    useradd -r -s /usr/sbin/nologin -g france-nuage-agent france-nuage-agent
 fi
 echo "User and group created"
+
 # Create the log directory and set permissions
 LOG_DIR="/var/log/france-nuage-agent"
 LOG_FILE="$LOG_DIR/metrics.logs"
-sudo mkdir -p $LOG_DIR
-sudo touch $LOG_FILE
-sudo chown france-nuage-agent:france-nuage-agent $LOG_DIR $LOG_FILE
-sudo chmod 755 $LOG_DIR
-sudo chmod 644 $LOG_FILE
+mkdir -p "$LOG_DIR"
+touch "$LOG_FILE"
+chown france-nuage-agent:france-nuage-agent "$LOG_DIR" "$LOG_FILE"
+chmod 755 "$LOG_DIR"
+chmod 644 "$LOG_FILE"
 
 cd /opt/france-nuage-agent
+
+# Ensure correct permissions
+chown -R france-nuage-agent:france-nuage-agent /opt/france-nuage-agent
+
+# Remove existing node_modules and package-lock.json
+rm -rf node_modules package-lock.json
+
 # Clear npm cache
 npm cache clean --force
-# Install npm dependencies
-if ! npm install; then
+
+# Reinstall dependencies
+if ! npm install --legacy-peer-deps; then
     echo "npm install failed"
     exit 1
-else
-    echo "npm install succeeded"
+fi
+
+# Compile TypeScript files
+if ! npx tsc; then
+    echo "TypeScript compilation failed"
+    exit 1
 fi
 
 # Reload systemd manager configuration
-sudo systemctl daemon-reload
+systemctl daemon-reload
 
 # Enable and start the service
-sudo systemctl enable france-nuage-agent.service
-sudo systemctl start france-nuage-agent.service
+systemctl enable france-nuage-agent.service
+systemctl start france-nuage-agent.service
 echo "Post-installation script completed successfully"
